// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72jyfa-YFCJW7iT_ye5dBmjQnywdAyVU',
    appId: '1:558178861433:android:34f5296b424780ac01efa8',
    messagingSenderId: '558178861433',
    projectId: 'dostum-nerede-app',
    storageBucket: 'dostum-nerede-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4jGYzDp76svSRsVlrsnadhgr0di9JITU',
    appId: '1:558178861433:ios:922364ddb6b4c82c01efa8',
    messagingSenderId: '558178861433',
    projectId: 'dostum-nerede-app',
    storageBucket: 'dostum-nerede-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4RLvWkH-EJfpPost__CHpA-JxvydeXLU',
    appId: '1:558178861433:web:954b2d11772db48201efa8',
    messagingSenderId: '558178861433',
    projectId: 'dostum-nerede-app',
    authDomain: 'dostum-nerede-app.firebaseapp.com',
    storageBucket: 'dostum-nerede-app.firebasestorage.app',
    measurementId: 'G-7FMVQBBW3N',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4RLvWkH-EJfpPost__CHpA-JxvydeXLU',
    appId: '1:558178861433:web:be52e6c488782f4d01efa8',
    messagingSenderId: '558178861433',
    projectId: 'dostum-nerede-app',
    authDomain: 'dostum-nerede-app.firebaseapp.com',
    storageBucket: 'dostum-nerede-app.firebasestorage.app',
    measurementId: 'G-1269ZB2215',
  );

}